name: rebootstrap-raft
base: core24
adopt-info: rebootstrap-raft
summary: Recovery tool for broken Juju raft clusters
description: |
  `rebootstrap-raft` creates an empty raft cluster directory with server
  configuration based on the current replicaset members. It's intended as
  an emergency utility to resolve situations where the raft store has been
  corrupted somehow.

  For safety, it won't overwrite raft data—any existing raft directory
  `/var/lib/juju/raft` will need to be removed or renamed. The new raft
  directory won't have any lease information in it, but if the Juju
  controller is part of an HA cluster and the other nodes still have lease
  information, it will be replicated to this one when the controller agent
  is started.


grade: stable
confinement: strict

apps:
  rebootstrap-raft:
    command: bin/rebootstrap-raft

parts:
  rebootstrap-raft:
    plugin: go
    source: .
    build-environment:
      # Disable CGO so that we get a static binary
      - CGO_ENABLED: "0"
    build-snaps:
      - go
    build-packages:
      - git
    override-pull: |
      set -e -u -x
      craftctl default
      craftctl set version=$(git describe --tags)
